services:
  webserver:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/dbms_project
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=shop_tester
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=dbms_project
    # volumes:
    #   - mysql_data:/var/lib/mysql
    #   - mysql_config:/etc/mysql/conf.d
# volumes:
#   mysql_data:
#   mysql_config: